### ISSUE TITLE
I keep having the error ModuleNotFoundError: No module named 'pynm.models'

### ISSUE THREAD

**Issue by SmailDK** [ppsp-team/PyNM#19]
When importing PyNM from pynm.pynm, I always have the error 

ModuleNotFoundError: No module named 'pynm.models'

![image](https://user-images.githubusercontent.com/98106419/171626312-d67d018d-8b91-4ea5-b37c-4e3f98fd1b8d.png)

Do you have a solution for this issue ?

Thanks in advance

**Comment by deep-introspection** [comment]
If you use the latest version on Github, it should work. We will update the package on Pypi shortly.

**Comment by deep-introspection** [comment]
It should be fine also with pip now.
