### ISSUE TITLE
documentation for testing

### ISSUE THREAD

**Issue by saigerutherford** [ppsp-team/PyNM#23]
There is no documentation on how to test, and this is a requirement on the [JOSS checklist](https://github.com/openjournals/joss-reviews/issues/4321). When running `test/test_pynm.py` I also get an error message that the pytest package is not installed in my virtual environment, so this package should be added to `requirements.txt` and some documentation for how to run tests should be added to the repository.

**Comment by harveyaa** [comment]
Hi @saigerutherford, I added pytest to `requirements.txt` and a section to the `README.md` entitled "How to run tests" for documentation on testing the code.
