### ISSUE TITLE
false claim regarding PCNtoolkit usability for beginners

### ISSUE THREAD

**Issue by saigerutherford** [ppsp-team/PyNM#25]
Re: [JOSS review](https://github.com/openjournals/joss-reviews/issues/4321)

In the paper, there is a sentence about the PCNToolkit stating: "While it includes features that make it an obvious choice for advanced users in many cases, is not as approachable to beginners and does not implement several key models." 

From my perspective, this is an unfair critique. Instead of a vague/general statement that your package is more approachable to beginners (which you do not make clear how it is more approachable to beginners), I think it is more productive to focus on specific examples of how your package is different from the PCNToolkit, like implementing different algorithms (i.e., GAMLSS). 

I do have to admit that I am biased here, because in my Ph.D. I have invested tons of time to make the PCNToolkit accessible to beginners with an in-depth [protocol paper](https://t.co/pm4wVBpuXV), lots of [tutorials](https://pcntoolkit.readthedocs.io/en/latest/pages/BLR_normativemodel_protocol.html) that are easily accessible in a web browser (no local python install required), a [forum](https://gitter.im/predictive-clinical-neuroscience/community) for communication/asking questions, etc. 

So, while I think that your package does have certain benefits that should be highlighted, I do not agree that it is more accessible for beginners than the PCNToolkit.

**Comment by harveyaa** [comment]
Hi @saigerutherford, I updated the paper to read:

"To the author’s knowledge, PCNtoolkit [@pcntoolkit] is the only other available package for Normative Modeling. It implements methods that have been applied in a range of psychiatry and neuroimaging studies including [@kia:2020], [@kia:2021], [@rutherford:2022a] and [@fraza:2021], and is accompanied by thorough [tutorials](https://pcntoolkit.readthedocs.io/en/latest/pages/BLR_normativemodel_protocol.html), a [forum](https://gitter.im/predictive-clinical-neuroscience/community), and a framework for Normative Modeling in computational psychiatry [@rutherford:2022b]. While PCNtoolkit offers more advanced functionality, PyNM emphasizes being lightweight and easy to use, and implements different models than PCNtookit including the GAMLSS which is a powerful option for Normative Modeling [@dinga:2021]."

Which removes the critique in favour of highlighting the accompanying paper, forum and tutorials (that make PCNtoolkit accessible to beginners) and mentioning pynm's differences from PCNtoolkit.
