### ISSUE TITLE
Normative Modeling for longitudinal data

### ISSUE THREAD

**Issue by GalBenZvi** [ppsp-team/PyNM#31]
Hi,
I was wondering if it's possible to use normative modeling to detect the effects of an intervention in longitudinal studies.

That is, say we have 2 measurements of the "score" variables per subject, can I refer to the time point ("pre"/"post" intervention) as the grouping variable? or is there an assumption of independence between measurements?

The reason I think it may work is that if you have different "scores" (derived from different brain regions), I would assume that the "post" group will be more different than the "pre" group in regions more affected by the intervention, so I can refer to the "pre" group as controls...

Thanks in advance!

**Comment by deep-introspection** [comment]
That's a very good question! For longitudinal data, I thought you would use the normative model on controls and then use the delta between the two pre/post normative scores of your participants as the variable of interest. But I think your idea should also work! Maybe @harveyaa has more thoughts on this.

**Comment by harveyaa** [comment]
Hi, I don’t think there would be any issues with independence between the two groups since it’s just asking how well the estimated model applies to unseen data. All the observations the model is fit on initially are independent, and that’s the only point where I would be suspicious of violating assumptions.

**Comment by GalBenZvi** [comment]
Thanks for the prompt reply @deep-introspection and @harveyaa!

> Hi, I don’t think there would be any issues with independence between the two groups since it’s just asking how well the estimated model applies to unseen data. All the observations the model is fit on initially are independent, and that’s the only point where I would be suspicious of violating assumptions.

So does this mean that the "training" set (i.e, controls) must be cross-sectional? Because otherwise, in the case where controls are also repeated measures, observations are not independent.

Maybe the training set should consist of the **difference** between subjects' observations, rather than the observations themselves?

**Comment by deep-introspection** [comment]
Exactly, I was more heading toward applying normative modeling to the difference. But in that case, it may be only feasible with fixed time difference. For more complex design, one can also assume the « ergodicity » of the control population.
