### ISSUE TITLE
How to deal with categorical variables with Gaussian process regression?

### ISSUE THREAD

**Issue by ruiyangge** [ppsp-team/PyNM#37]
Hi there,  I'm curious about how you handle categorical variables, such as 'site,' when using Gaussian process regression. Do you employ a specific method tailored for GPR in this context? I'm asking because conventional GPR assumes continuous input variables. Thanks.

**Comment by deep-introspection** [comment]
Hi! You can still use a one-hot encoding scheme. See this paper for more details: https://arxiv.org/abs/1805.03463 or also this scikit-learn tutorial: https://scikit-learn.org/stable/auto_examples/gaussian_process/plot_gpr_on_structured_data.html
